config/routes.rb
Proyecto::Application.routes.draw do
  
  post "add_article_to_order/article/:article_id/order/:order_id" => "articles#add_article_to_order", :as => :crear_articulos_orden
  resources :order_statuses

  resources :departments

  resources :payment_statuses

  resources :orders

  resources :retail_units

  resources :articles

  resources :clients

end

app/controllers/order_statuses_controller.rb
class OrderStatusesController < ApplicationController
  # GET /order_statuses
  # GET /order_statuses.json
  def index
    @order_statuses = OrderStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @order_statuses }
    end
  end

  # GET /order_statuses/1
  # GET /order_statuses/1.json
  def show
    @order_status = OrderStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order_status }
    end
  end

  # GET /order_statuses/new
  # GET /order_statuses/new.json
  def new
    @order_status = OrderStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order_status }
    end
  end

  # GET /order_statuses/1/edit
  def edit
    @order_status = OrderStatus.find(params[:id])
  end

  # POST /order_statuses
  # POST /order_statuses.json
  def create
    @order_status = OrderStatus.new(params[:order_status])

    respond_to do |format|
      if @order_status.save
        format.html { redirect_to @order_status, notice: 'Order status was successfully created.' }
        format.json { render json: @order_status, status: :created, location: @order_status }
      else
        format.html { render action: "new" }
        format.json { render json: @order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /order_statuses/1
  # PUT /order_statuses/1.json
  def update
    @order_status = OrderStatus.find(params[:id])

    respond_to do |format|
      if @order_status.update_attributes(params[:order_status])
        format.html { redirect_to @order_status, notice: 'Order status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_statuses/1
  # DELETE /order_statuses/1.json
  def destroy
    @order_status = OrderStatus.find(params[:id])
    @order_status.destroy

    respond_to do |format|
      format.html { redirect_to order_statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/order_statuses_helper.rb
module OrderStatusesHelper
end

app/views/order_statuses/_form.html.erb
<%= form_for(@order_status) do |f| %>
  <% if @order_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_status.errors.count, "error") %> prohibited this order_status from being saved:</h2>

      <ul>
      <% @order_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_statuses/edit.html.erb
<h1>Editing order_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_status %> |
<%= link_to 'Back', order_statuses_path %>

app/views/order_statuses/index.html.erb
<h1>Listing order_statuses</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @order_statuses.each do |order_status| %>
  <tr>
    <td><%= order_status.nombre %></td>
    <td><%= order_status.descripcion %></td>
    <td><%= link_to 'Show', order_status %></td>
    <td><%= link_to 'Edit', edit_order_status_path(order_status) %></td>
    <td><%= link_to 'Destroy', order_status, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order status', new_order_status_path %>

app/views/order_statuses/new.html.erb
<h1>New order_status</h1>

<%= render 'form' %>

<%= link_to 'Back', order_statuses_path %>

app/views/order_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @order_status.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @order_status.descripcion %>
</p>


<%= link_to 'Edit', edit_order_status_path(@order_status) %> |
<%= link_to 'Back', order_statuses_path %>