config/routes.rb
Proyecto::Application.routes.draw do
  
  post "add_article_to_order/article/:article_id/order/:order_id" => "articles#add_article_to_order", :as => :crear_articulos_orden
  resources :order_statuses

  resources :departments

  resources :payment_statuses

  resources :orders

  resources :retail_units

  resources :articles

  resources :clients

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :department_id, :marca, :nombre, :precio_por_unidad_de_venta, :retail_unit_id, :stock
  belongs_to :department
  has_and_belongs_to_many :orders
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end
  
  def add_article_to_order
    ArticlesOrder.create(:article_id => params[:article_id], :order_id => 1, :cantidad => 2)
    respond_to do |format|
      format.js
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def get_order
        
  end
end

app/views/articles/_form.html.erb
<br />
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :marca %><br />
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br />
    <%= f.collection_select(:department_id, Department.all, :id, :nombre) %>
  </div>
  <div class="field">
    <%= f.label :retail_unit_id %><br />
    <%= f.collection_select(:retail_unit_id, RetailUnit.all, :id, :nombre) %>
  </div>
  <div class="field">
    <%= f.label :precio_por_unidad_de_venta %><br />
    <%= f.text_field :precio_por_unidad_de_venta %>
  </div>
  <div class="field">
    <%= f.label :stock %><br />
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit params[:action] == "edit" ? "Actualizar Departamento" : "Crear Departamento" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edicion de articulos</h1>

<%= render 'form' %>

<%= link_to 'Ver detalles', @article %> |
<%= link_to 'Lista de articulos', articles_path %>

app/views/articles/index.html.erb
<script>
	

    $(document).ready(function() {
        $(".cantidad").hide();
    });

	function mostrar_div_cantidad(article_id){
		$("#cantidad_articulo_" + article_id).show();
		$("#agregar_articulo_" + article_id).hide();
	}
	
	function ocultar_div_cantidad(article_id){
		$("#cantidad_articulo_" + article_id).hide();
		$("#agregar_articulo_" + article_id).show();
	}

</script>
<h1>Lista de articulos</h1>

<table class="table">
  <tr>
    <th>Nombre</th>
    
    <th>Departamento</th>
    <th>Unidad</th>
    <th>Precio </th>
    <th>Stock</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
  	
    <td><%= article.nombre %></td>
    <td><%= article.department_id %></td>
    <td><%= article.retail_unit_id %></td>
    
    <td><%= article.precio_por_unidad_de_venta %></td>
    <td><%= article.stock %></td>
    <td><%= link_to 'Ver detalles', article %></td>
    <td><%= link_to 'Editar', edit_article_path(article) %></td>
    <td><%= link_to 'Eliminar', article, confirm: 'Esta seguro?', method: :delete %></td>
    <td id="cantidad_articulo_<%= article.id %>" class="cantidad"> <label>Cantidad:</label><input type="number" style="width: 20px;" /><div><%= link_to "Agregar", crear_articulos_orden_url(article.id,1), :method => :post, :remote => true, :format => :js	 %> <label onclick="ocultar_div_cantidad(<%= article.id%>);">Ocultar</label></div></dir></td>
 	<td id="agregar_articulo_<%= article.id %>"><label href="#" onclick="mostrar_div_cantidad(<%= article.id %>);">Agregar</label></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Crear u nuevo articulo', new_article_path %>

app/views/articles/new.html.erb
<h1>Nuevo Articulo</h1>

<%= render 'form' %>

<%= link_to 'Lista de ariculos', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @article.nombre %>
</p>

<p>
  <b>Marca:</b>
  <%= @article.marca %>
</p>

<p>
  <b>Departamento:</b>
  <%= @article.department_id %>
</p>

<p>
  <b>unidad:</b>
  <%= @article.retail_unit_id %>
</p>

<p>
  <b>Precio por unidad de venta:</b>
  <%= @article.precio_por_unidad_de_venta %>
</p>

<p>
  <b>Stock:</b>
  <%= @article.stock %>
</p>


<%= link_to 'Editar', edit_article_path(@article) %> |
<%= link_to 'Lista de articulos', articles_path %>