config/routes.rb
Proyecto::Application.routes.draw do
  
  post "add_article_to_order/article/:article_id/order/:order_id" => "articles#add_article_to_order", :as => :crear_articulos_orden
  resources :order_statuses

  resources :departments

  resources :payment_statuses

  resources :orders

  resources :retail_units

  resources :articles

  resources :clients

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :apellido_materno, :apellido_paterno, :calle, :ciudad_id, :email, :estado_id, :nombre, :numero_exterior, :numero_interior
  has_many :orders
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido_paterno %><br />
    <%= f.text_field :apellido_paterno %>
  </div>
  <div class="field">
    <%= f.label :apellido_materno %><br />
    <%= f.text_field :apellido_materno %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :calle %><br />
    <%= f.text_field :calle %>
  </div>
  <div class="field">
    <%= f.label :numero_exterior %><br />
    <%= f.number_field :numero_exterior %>
  </div>
  <div class="field">
    <%= f.label :numero_interior %><br />
    <%= f.number_field :numero_interior %>
  </div>
  <div class="field">
    <%= f.label :ciudad_id %><br />
    <%= f.number_field :ciudad_id %>
  </div>
  <div class="field">
    <%= f.label :estado_id %><br />
    <%= f.number_field :estado_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido paterno</th>
    <th>Apellido materno</th>
    <th>Email</th>
    <th>Calle</th>
    <th>Numero exterior</th>
    <th>Numero interior</th>
    <th>Ciudad</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.nombre %></td>
    <td><%= client.apellido_paterno %></td>
    <td><%= client.apellido_materno %></td>
    <td><%= client.email %></td>
    <td><%= client.calle %></td>
    <td><%= client.numero_exterior %></td>
    <td><%= client.numero_interior %></td>
    <td><%= client.ciudad_id %></td>
    <td><%= client.estado_id %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @client.nombre %>
</p>

<p>
  <b>Apellido paterno:</b>
  <%= @client.apellido_paterno %>
</p>

<p>
  <b>Apellido materno:</b>
  <%= @client.apellido_materno %>
</p>

<p>
  <b>Email:</b>
  <%= @client.email %>
</p>

<p>
  <b>Calle:</b>
  <%= @client.calle %>
</p>

<p>
  <b>Numero exterior:</b>
  <%= @client.numero_exterior %>
</p>

<p>
  <b>Numero interior:</b>
  <%= @client.numero_interior %>
</p>

<p>
  <b>Ciudad:</b>
  <%= @client.ciudad_id %>
</p>

<p>
  <b>Estado:</b>
  <%= @client.estado_id %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>