config/routes.rb
Proyecto::Application.routes.draw do
  
  post "add_article_to_order/article/:article_id/order/:order_id" => "articles#add_article_to_order", :as => :crear_articulos_orden
  resources :order_statuses

  resources :departments

  resources :payment_statuses

  resources :orders

  resources :retail_units

  resources :articles

  resources :clients

end

app/models/retail_unit.rb
class RetailUnit < ActiveRecord::Base
  attr_accessible :descripcion, :nombre, :tipo
end

app/controllers/retail_units_controller.rb
class RetailUnitsController < ApplicationController
  # GET /retail_units
  # GET /retail_units.json
  def index
    @retail_units = RetailUnit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @retail_units }
    end
  end

  # GET /retail_units/1
  # GET /retail_units/1.json
  def show
    @retail_unit = RetailUnit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @retail_unit }
    end
  end

  # GET /retail_units/new
  # GET /retail_units/new.json
  def new
    @retail_unit = RetailUnit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @retail_unit }
    end
  end

  # GET /retail_units/1/edit
  def edit
    @retail_unit = RetailUnit.find(params[:id])
  end

  # POST /retail_units
  # POST /retail_units.json
  def create
    @retail_unit = RetailUnit.new(params[:retail_unit])

    respond_to do |format|
      if @retail_unit.save
        format.html { redirect_to @retail_unit, notice: 'Retail unit was successfully created.' }
        format.json { render json: @retail_unit, status: :created, location: @retail_unit }
      else
        format.html { render action: "new" }
        format.json { render json: @retail_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /retail_units/1
  # PUT /retail_units/1.json
  def update
    @retail_unit = RetailUnit.find(params[:id])

    respond_to do |format|
      if @retail_unit.update_attributes(params[:retail_unit])
        format.html { redirect_to @retail_unit, notice: 'Retail unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @retail_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retail_units/1
  # DELETE /retail_units/1.json
  def destroy
    @retail_unit = RetailUnit.find(params[:id])
    @retail_unit.destroy

    respond_to do |format|
      format.html { redirect_to retail_units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/retail_units_helper.rb
module RetailUnitsHelper
end

app/views/retail_units/_form.html.erb
<%= form_for(@retail_unit) do |f| %>
  <% if @retail_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retail_unit.errors.count, "error") %> prohibited this retail_unit from being saved:</h2>

      <ul>
      <% @retail_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit params[:action] == "edit" ? "Actualizar Departamento" : "Crear Departamento" %>
  </div>
<% end %>

app/views/retail_units/edit.html.erb
<h1>Edicion de unidades</h1>

<%= render 'form' %>

<%= link_to 'Ver detalles', @retail_unit %> |
<%= link_to 'Lista de unidades', retail_units_path %>

app/views/retail_units/index.html.erb
<h1>Lista de unidades</h1>

<table class="table">
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Tipo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @retail_units.each do |retail_unit| %>
  <tr>
    <td><%= retail_unit.nombre %></td>
    <td><%= retail_unit.descripcion %></td>
    <td><%= retail_unit.tipo %></td>
    <td><%= link_to 'Ver detalles', retail_unit %></td>
    <td><%= link_to 'Editar', edit_retail_unit_path(retail_unit) %></td>
    <td><%= link_to 'Eliminar', retail_unit, confirm: 'Esta seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Retail unit', new_retail_unit_path %>

app/views/retail_units/new.html.erb
<h1>Nueva unidad</h1>

<%= render 'form' %>

<%= link_to 'Lista de unidades', retail_units_path %>

app/views/retail_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @retail_unit.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @retail_unit.descripcion %>
</p>

<p>
  <b>Tipo:</b>
  <%= @retail_unit.tipo %>
</p>


<%= link_to 'Editar', edit_retail_unit_path(@retail_unit) %> |
<%= link_to 'Lista de unidades', retail_units_path %>